# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

kind-dependencies:
    - instrumented-build

transforms:
    - taskgraph.transforms.build_attrs:transforms
    - taskgraph.transforms.release_deps:transforms
    - taskgraph.transforms.run_pgo_profile:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms


job-defaults:
    treeherder:
        symbol: Bpgo(run)
        kind: test
        tier: 1

jobs:
    linux64/pgo:
        description: "Linux64 Profile Generation"
        shipping-phase: build
        shipping-product: firefox
        index:
            product: firefox
            job-name: linux64-profile
        treeherder:
            platform: linux64/pgo
        worker-type: aws-provisioner-v1/gecko-{level}-b-linux
        worker:
            max-run-time: 1200
            docker-image: {in-tree: debian9-amd64-build}
            artifacts:
                - type: file
                  name: public/build/profdata.tar.xz
                  path: /builds/worker/artifacts/profdata.tar.xz
                - type: file
                  name: public/build/xvfb.log
                  path: /builds/worker/artifacts/xvfb/xvfb.log
                - type: file
                  name: public/build/profile-run-1.log
                  path: /builds/worker/artifacts/profile-run-1.log
                - type: file
                  name: public/build/profile-run-2.log
                  path: /builds/worker/artifacts/profile-run-2.log
        run:
            using: run-task
            command: >
                cd /builds/worker/checkouts/gecko &&
                ./taskcluster/scripts/misc/run-profileserver.sh
