# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.release_snap_push:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - release-snap-repackage

job-defaults:
   description: Pushes (Ubuntu) Snaps onto Snap Store
   run-on-projects: []  # to make sure this never runs as part of CI
   shipping-phase: push
   scopes:
      by-project:
         mozilla-beta: ["project:releng:snapcraft:firefox:beta"]
         mozilla-release: ["project:releng:snapcraft:firefox:candidate"]
         mozilla-esr60: ["project:releng:snapcraft:firefox:esr"]
         default: ["project:releng:snapcraft:firefox:mock"]
   treeherder:
      platform: linux64/opt
      kind: build
      tier: 2
   worker-type:
      by-release-level:
         production: scriptworker-prov-v1/pushsnap-v1
         staging: scriptworker-prov-v1/dep-pushsnap
   worker:
      implementation: push-snap

jobs:
   firefox:
      shipping-product: firefox
      treeherder:
         symbol: Snap(push)
