## Docs-specific linter rules

rules:
  object-curly-spacing: [2, always]

  # ease some restrictions in doc examples
  no-restricted-properties: 0
  no-undef: 0
  no-unused-vars: 0
  strict: 0

  # add new ECMAScript features gradually
  no-var: 2
  prefer-const: 2
  prefer-rest-params: 2

  # use stricter indent over indent-legacy
  indent-legacy: 0
  indent: [2, 2, {ArrayExpression: first,
                  CallExpression: {arguments: first},
                  FunctionDeclaration: {parameters: first},
                  FunctionExpression: {parameters: first},
                  MemberExpression: off,
                  ObjectExpression: first,
                  SwitchCase: 1}]
