## Docs-specific linter rules

rules:
  object-curly-spacing: [error, always]

  # ease some restrictions in doc examples
  no-restricted-properties: off
  no-undef: off
  no-unused-vars: off
  strict: off

  # add new ECMAScript features gradually
  no-var: error
  prefer-const: error
  prefer-rest-params: error

  # use stricter indent over indent-legacy
  indent-legacy: off
  indent: [error, 2, {ArrayExpression: first,
                      CallExpression: {arguments: first},
                      FunctionDeclaration: {parameters: first},
                      FunctionExpression: {parameters: first},
                      MemberExpression: off,
                      ObjectExpression: first,
                      SwitchCase: 1}]
