# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.release_deps:transforms
    - taskgraph.transforms.release_version_bump:transforms
    - taskgraph.transforms.task:transforms

kind-dependencies:
    - release-beetmover-push-to-release

job-defaults:
    description: Release Promotion version bump/tag
    run-on-projects: []
    shipping-phase: ship
    worker-type:
        by-project:
            mozilla-(beta|release|esr.*): scriptworker-prov-v1/treescript-v1
            maple: scriptworker-prov-v1/treescript-v1
            birch: scriptworker-prov-v1/treescript-v1
            jamun: scriptworker-prov-v1/treescript-v1
            default: scriptworker-prov-v1/treescript-dev
    worker:
        implementation: treescript
        dontbuild: true
        tags: ['release']
        bump: true
        bump-files:
            by-project:
                default: ["browser/config/version_display.txt"]
                mozilla-release:
                    - "browser/config/version.txt"
                    - "browser/config/version_display.txt"
                    - "config/milestone.txt"
                mozilla-esr52:
                    - "browser/config/version.txt"
                    - "browser/config/version_display.txt"
                    - "config/milestone.txt"
                mozilla-esr60:
                    - "browser/config/version.txt"
                    - "browser/config/version_display.txt"
                    - "config/milestone.txt"
                jamun:
                    - "browser/config/version.txt"
                    - "browser/config/version_display.txt"
                    - "config/milestone.txt"
        push:
            by-project:
                mozilla-beta: true
                mozilla-release: true
                mozilla-esr52: true
                mozilla-esr60: true
                maple: true
                birch: true
                jamun: true
                default: false

jobs:
    fennec:
        name: fennec-version-bump
        shipping-product: fennec

    firefox:
        name: firefox-version-bump
        shipping-product: firefox

    devedition:
        name: devedition-version-bump
        shipping-product: devedition
