## Tools-specific linter rules

rules:
  # Stylistic Issues
  # http://eslint.org/docs/rules/#stylistic-issues
  indent: [2, 2, {ArrayExpression: first,
                  CallExpression: {arguments: first},
                  FunctionDeclaration: {parameters: first},
                  FunctionExpression: {parameters: first},
                  MemberExpression: off,
                  ObjectExpression: first,
                  SwitchCase: 1}]
