# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

loader: taskgraph.loader.transform:loader

transforms:
   - taskgraph.transforms.release_deps:transforms
   - taskgraph.transforms.release_snap_repackage:transforms
   - taskgraph.transforms.task:transforms

kind-dependencies:
   - post-beetmover-dummy
   - post-langpack-dummy

job-defaults:
   description: Generates snap image
   run-on-projects: []  # to make sure this never runs as part of CI
   shipping-phase: promote
   scopes: []
   treeherder:
      platform: linux64/opt
      kind: build
      tier: 2
   worker-type: aws-provisioner-v1/gecko-{level}-b-linux
   worker:
      implementation: docker-worker
      os: linux
      max-run-time: 7200
      docker-image: {in-tree: firefox-snap}
      artifacts:
         - name: public/build
           type: directory
           path: /home/worker/artifacts/
      command:
         - /bin/bash
         - -cx
         - >
           curl -o scripts.tar.bz2 {config_params[head_repository]}/archive/{config_params[head_rev]}.tar.bz2/taskcluster/docker/firefox-snap/ &&
           mkdir scripts &&
           tar xvfj scripts.tar.bz2 -C scripts --strip-components 4 &&
           cd scripts &&
           ./runme.sh
      env:
         VERSION: "{release_config[version]}"
         BUILD_NUMBER: "{release_config[build_number]}"
         CANDIDATES_DIR:
            by-release-level:
               staging:
                  https://net-mozaws-stage-delivery-firefox.s3.amazonaws.com/pub/{task[shipping-product]}/candidates
               production:
                  https://net-mozaws-prod-delivery-firefox.s3.amazonaws.com/pub/{task[shipping-product]}/candidates
         LC_ALL: C.UTF-8
         LANG: C.UTF-8
         L10N_CHANGESETS: "{config_params[head_repository]}/raw-file/{config_params[head_rev]}/browser/locales/l10n-changesets.json"
      chain-of-trust: true

jobs:
   firefox:
      shipping-product: firefox
      attributes:
         build_platform: linux64-nightly
      treeherder:
         symbol: Snap(r)
